<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Joaquins-MacBook-Pro.local" ignored="0" name="User Tests" tests="4" failures="2" timestamp="08 Nov 2022 18:32:19 GMT" time="0.439" errors="0">
  <testcase name="example1" time="0.193" classname="com.mycompany.app.AppTest">
    <failure type="java.lang.AssertionError" message="This test should be failed expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: This test should be failed expected [3] but found [2]
at com.mycompany.app.AppTest.example1(AppTest.java:10)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- example1 -->
  <testcase name="example2" time="0.002" classname="com.mycompany.app.AppTest"/>
  <testcase name="example3" time="0.001" classname="com.mycompany.app.AppTest"/>
  <testcase name="example4" time="0.001" classname="com.mycompany.app.AppTest">
    <failure type="java.lang.AssertionError" message="This test should be failed">
      <![CDATA[java.lang.AssertionError: This test should be failed
at com.mycompany.app.AppTest.example4(AppTest.java:25)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- example4 -->
</testsuite> <!-- User Tests -->
